feat: 생성시간 및 수정시간 관리를 위해 JPA Auditing 적용
EDD-season2/caffeine-be pull request #12
Opened 2019-12-06 12:42 UTC by Conatuseus

Squashed commit of the following:

commit 81d1749a6e360c5427ef04a204c422ac8164c350
Author: MK S <conatuseus@gmail.com>
Date:   Fri Dec 6 21:39:47 2019 +0900

    refactor: 값 확인하기 위한 print 추가

commit 884074861bf854037bac29cbc84ac48996288ec7
Author: MK S <conatuseus@gmail.com>
Date:   Fri Dec 6 21:39:31 2019 +0900

    refactor: Order라는 테이블 생성에 문제가 있어 Table 어노테이션 추가 및 이름 부여

commit 8a85f12814a00eca8fba5d8cf739bf06f7185a2f
Author: MK S <conatuseus@gmail.com>
Date:   Fri Dec 6 21:38:52 2019 +0900

    feat: application yml 파일 작성

commit bd75625750746c799e77e343e6d64975938712b8
Author: MK S <conatuseus@gmail.com>
Date:   Fri Dec 6 21:17:41 2019 +0900

    feat: Order test 추가

commit cd21a3baee29a4a7875eec23f6aff1af1f79bb9f
Author: MK S <conatuseus@gmail.com>
Date:   Fri Dec 6 21:17:28 2019 +0900

    feat: Entity들의 createdDate, modifiedDate를 자동으로 관리하는 역할하는 BaseTimeEntity 클래스 추가

commit 848aaec3507c9a328f67aa1b38df2ca4f7f5942f
Author: MK S <conatuseus@gmail.com>
Date:   Fri Dec 6 21:16:53 2019 +0900

    feat: Order를 위한 엔티티, Repository 추가

commit fdf0bc276ed251a8c76fb1ba7b88d83bb38b65aa
Author: MK S <conatuseus@gmail.com>
Date:   Fri Dec 6 21:16:31 2019 +0900

    feat: JPA Auditing 활성화를 위한 어노테이션 추가

2019-12-06 13:11 UTC, yuyu154 requested changes

2019-12-06 13:11 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/CaffeineApplication.java
> +@EnableJpaAuditing
Shop 관련 테스트가 통과하지 않네요.
Shop 엔티티에서 BaseTimeEntity를 상속하거나 다른 방법을 쓰는게 좋을 것 같아요

2019-12-06 13:21 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/CaffeineApplication.java
> +@EnableJpaAuditing
JPA Auditing을 Enable하니까 ShopDocumentationTest 가 안되는군요...
ShopControllerTest는 통과하는 것으로 봐서  JPA Auditing과 ShopDocumentationTest의 관계를 좀 살펴보고 어떻게 고칠지 찾아봐야겠네요! 고마워요

2019-12-06 13:40 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/CaffeineApplication.java
> +@EnableJpaAuditing
(https://stackoverflow.com/questions/51467132/spring-webmvctest-with-enablejpa-annotation)

위 글을 참조해봐도 좋을 것 같습니다.

CaffeineApplication 클래스의 @EnableJapAuditing을 다른 클래스로 분리하면 좋을 것 같습니다. 

아래 예시로 했을 때 통과가 되는 것을 확인했습니다.

```
@Configuration
@EnableJpaAuditing
public class TestConfiguration {
}
```

2019-12-06 14:34 UTC, Laterality requested changes

2019-12-06 14:34 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/repository/OrderRepository.java
> +@Repository
불필요한 어노테이션인 것 같아요~

2019-12-06 14:34 UTC, Laterality commented on src/test/resources/application.yml
> +      ddl-auto: create
파일 끝에 빈 줄을 남길 지도 컨벤션으로 정해보면 좋을 것 같아요!

2019-12-09 04:58 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/repository/OrderRepository.java
> +@Repository
수정했습니다~!

2019-12-09 04:59 UTC, Conatuseus commented on src/test/resources/application.yml
> +      ddl-auto: create
yml 파일 끝에 빈 줄을 남기는게 보통 컨벤션인가요?
일단 공백줄 추가 해놨습니다.

2019-12-09 07:49 UTC, yuyu154 approved these changes

2019-12-10 01:22 UTC, Laterality requested changes

2019-12-10 01:22 UTC, Laterality commented on src/test/java/com/woowacourse/caffeine/domain/OrderTest.java
> +        System.out.println(">>>>> createDate = "+order.getCreatedDate() + ", modifiedDate = "+order.getModifiedDate());
불필요한 코드인 것 같아요

2019-12-10 02:03 UTC, Conatuseus commented on src/test/java/com/woowacourse/caffeine/domain/OrderTest.java
> +        System.out.println(">>>>> createDate = "+order.getCreatedDate() + ", modifiedDate = "+order.getModifiedDate());
확인했습니다.

2019-12-10 02:03 UTC, merged