알림 서비스 구현
EDD-season2/caffeine-be pull request #17
Opened 2019-12-09 12:49 UTC by Laterality

SSE 방식의 사용자 알림 서비스 구현입니다.

테스트를 위한 알림 구독, 전송 컨트롤러를 추가할까 고민해봤는데, 구독 방식은 다른 서비스 구현에 따라 바뀔 것 같고, 전송 기능도 테스트 단계에서만 필요할 것 같아 따로 추가하진 않았습니다.

2019-12-10 01:56 UTC, yuyu154 requested changes

2019-12-10 01:56 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/application/service/CustomerNotificationService.java
> +    public void send(final String customerid, final String message) {
customerid -> customerId

2019-12-10 01:56 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/application/service/NotificationService.java
> +class NotificationService<T> {
패키지 내에서 쓰이니까 NotificationInternalService는 어떻나요? 이건 그냥 제안이니까 고려 안하셔도 괜찮습니다.

2019-12-10 03:57 UTC, eunsukko approved these changes
수고하셨습니다~

2019-12-10 03:57 UTC, eunsukko commented on src/main/java/com/woowacourse/caffeine/WebMvcConfig.java
> +
빈줄이 있숩니다..!

2019-12-10 03:57 UTC, eunsukko commented on src/main/java/com/woowacourse/caffeine/application/service/NotificationService.java
> +            subscriptions.remove(id);
```suggestion
            remove(id)
```
제거하는 부분을 private  remove(id) 로 표현하셨던거 같아서요

2019-12-10 03:57 UTC, eunsukko commented on src/main/java/com/woowacourse/caffeine/application/service/NotificationService.java
> +    private boolean putPendingIfNotSubscribing(final T id, final String message, final ResponseBodyEmitter emitter) {
```suggestion
    private void putPendingIfNotSubscribing(final T id, final String message, final ResponseBodyEmitter emitter) {
```
리턴으로 결과를 알려줄 필요없이
그냥 `IfNotSubscribing` 인 경우이면 put 하면 될 것 같아요 (저는 메소드 명이 그렇게 느껴져서리요)

2019-12-10 03:57 UTC, eunsukko commented on src/main/java/com/woowacourse/caffeine/application/service/NotificationService.java
> +            if (putPendingIfNotSubscribing(id, message, emitter)) return;
밑에 피드백과 연관지어서 보면..
```suggestion
            putPendingIfNotSubscribing(id, message, emitter); 
```

요 느낌이겠네요

2019-12-10 03:57 UTC, eunsukko commented on src/main/java/com/woowacourse/caffeine/application/service/NotificationService.java
> +        emitter.onCompletion(remove(id));
`onCompletion, onTimeout`들도 로그를 남겨주면 좋을 것 같아요 (팀에서 문제를 파악하기에요)

2019-12-10 03:57 UTC, eunsukko commented on src/main/java/com/woowacourse/caffeine/application/service/NotificationService.java
> +            e.printStackTrace();
logger.error 부탁드려요~ (나중에 로그를 파일에 쓰거나 할 수 있을 것 같아요)

2019-12-10 04:10 UTC, Conatuseus approved these changes
다른 분들이 이미 리뷰를 잘 해주셨네요.,
고생하셨어요 에단 💯

2019-12-10 04:10 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/application/service/CustomerNotificationService.java
> +    private NotificationService<String> notificationService = new NotificationService<>();
final 변수로 선언해도 될 것 같아요

2019-12-11 00:03 UTC, yuyu154 approved these changes

2019-12-11 00:12 UTC, merged