[Feature] Shop API (매장 관련 API 구현)
EDD-season2/caffeine-be pull request #19
Opened 2019-12-10 01:40 UTC by yuyu154

1. Shop Entity의 모든 컬럼이 String 값인 상태.
 - 차후에 주소, 전화번호를 객체로 만들 예정
 - 이미지도 다른 방식으로 저장하는 것 고려할 예정

2. /v1/shop -> /v1/shops/ 로 변경함

2019-12-10 03:57 UTC, Conatuseus reviewed
고생하셨어요 르윈 💯  👍 
리뷰 보시고 궁금하신 것 생기면 말씀해주세요.

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/application/dto/ShopResponse.java
> +    private String name;
Response는 final을 사용하는게 좋지 않을까요?

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/application/dto/ShopResponse.java
> +    // image url
불필요한 주석 제거해도 될 것 같아요.

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/controller/ShopController.java
> +    public static final String V1_SHOP = "/v1/shops";
shops 로 수정 👍 💯

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/controller/ShopController.java
>      @GetMapping("/{id}")
`{id}` 보단 `{shopId}` 이렇게 명시적으로 하는 것은 어떨까요?
의견 나눠봐야 될 것 같아요

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/controller/ShopController.java
> +        ShopResponse foundedShopResponse = shopService.findById(id);
found가 이미 과거형이니 `foundShop` 이나 `foundShopResponse`로 하면 좋을 것 같아요

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/Shop.java
> +import javax.persistence.*;
와일드 카드 사용하지 않는 것이 좋다고 합니다.
https://stackoverflow.com/questions/147454/why-using-a-wild-card-with-a-java-import-statement-bad
읽어보시면 좋을 것 같아요.

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/Shop.java
> +
무의미한 공백이 한 줄 더 추가된 것 같아요

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/Shop.java
> +        if (StringUtils.isEmpty(imageUrl)) {
StringUtils 사용 👍

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/application/service/ShopService.java
> +        }
스트림을 사용하면 가독성을 더 높일 수 있을 것 같아요.

~~~ java
List<ShopResponse> shopResponses = shops.stream().map(shop -> new ShopResponse(shop.getId(), shop.getName(), shop.getImageUrl(), shop.getAddress(), shop.getPhoneNumber()))
            .collect(Collectors.toList());
        
List<ShopResponse> shopResponses = shops.stream().map(ShopConverter::toResponse)
        .collect(Collectors.toList());
~~~
위 코드는 Converter 사용하지 않은 것이고
 Converter를 구현한다면 아래와 같이 사용할 수 있을 것 같아요.

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/application/service/ShopService.java
> +            shop.getPhoneNumber());
Shop -> ShopResponse로 변경하는 부분이 몇 군데 보이는데
Converter나 편의 메서드를 구현하면 좋을 것 같아요

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/application/service/ShopService.java
> +    @Transactional(readOnly = true)
readOnly 설정 👍

2019-12-10 03:57 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/Shop.java
> +        }
`name`만 있는 생성자와   name을 체크하는 로직이 중복되는데
하나의 메서드로 빼서 두 군데에서 사용하면 좋을 것 같아요.

2019-12-10 04:03 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/Shop.java
> +import javax.persistence.*;
> intellij에서 와일드 카드 사용하지 않도록 설정할 수 있어요

2019-12-10 06:15 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/application/dto/ShopResponse.java
> +    private String name;
setter가 필요한 상황이라 제거하지 않았습니다

2019-12-10 07:16 UTC, Laterality requested changes

2019-12-10 07:16 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/service/ShopService.java
> +    private ShopConverter shopConverter;
생성자로 같이 주입받을 수 없나요?

2019-12-10 07:31 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/application/service/ShopService.java
> +    private ShopConverter shopConverter;
반영했습니다.

2019-12-10 08:40 UTC, Laterality requested changes

2019-12-10 08:40 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/dto/ShopCreateRequest.java
> +    public void setImage(String image) {
setter 인자가 어떤 건  `final`이 있고 어떤 건 없네요.

2019-12-10 08:40 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/dto/ShopResponse.java
>  public class ShopResponse {
한 줄 띄울까요?

2019-12-10 08:40 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/dto/ShopResponse.java
> +    public void setId(Long id) {
setter 인자에도 `final`을 사용하신다면 여기도 적용하면 좋을 것 같아요.

2019-12-10 08:40 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/dto/ShopResponses.java
> +public class ShopResponses {
한 줄 띄울까요?

2019-12-10 12:20 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/application/dto/ShopResponses.java
> +public class ShopResponses {
위부터 4개 리뷰해주신 것 반영했습니다.

2019-12-11 00:07 UTC, Laterality approved these changes

2019-12-11 00:33 UTC, merged