Payment Api 구현
EDD-season2/caffeine-be pull request #21
Opened 2019-12-10 06:10 UTC by kangmin46

* payment 과련 기능 구현입니다.
* 이후 외부 API를 사용해야할 경우에는 해당 기능 추가하겠습니다.

2019-12-10 06:43 UTC, yuyu154 approved these changes

2019-12-10 06:43 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/domain/payment/Payment.java
> +    @Id
한칸 띄어주세요

2019-12-10 07:08 UTC, Laterality requested changes

2019-12-10 07:08 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/dto/PaymentRequest.java
> +    private String way;
`paymentMethod`라는 이름은 어떠세요?

2019-12-10 07:08 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/dto/PaymentRequest.java
> +    public PaymentRequest(long id, long customerId, String way) {
`final`을 붙여보면 어떨까요?

2019-12-10 07:08 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/service/PaymentInternalService.java
> +public class PaymentInternalService {
한 줄을 띄워보면 어떨까요?

2019-12-10 07:08 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/controller/PaymentController.java
> +    private PaymentService paymentService;
생성자 주입을 사용하면 `final`을 붙일 수 있지 않을까요?

2019-12-10 07:08 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/exception/InvalidIdException.java
> +public class InvalidIdException extends RuntimeException {
한 줄을 띄워보면 어떨까요?

2019-12-10 07:08 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/exception/InvalidPaymentWayException.java
> +public class InvalidPaymentWayException extends RuntimeException {
한 띄 어?

2019-12-10 07:08 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/repository/PaymentRepository.java
> +@Repository
`@Repository` 어노테이션은 필요 없어도 될 것 같아요.

2019-12-10 07:08 UTC, Laterality commented on src/test/java/com/woowacourse/caffeine/controller/PaymentControllerTest.java
> +public class PaymentControllerTest {
ㅎ ㄸ ㅇ?

2019-12-10 07:19 UTC, kangmin46 commented on src/test/java/com/woowacourse/caffeine/controller/PaymentControllerTest.java
> +public class PaymentControllerTest {
반영했습니다~

2019-12-10 08:02 UTC, Conatuseus reviewed
의견 리뷰로 남겼어요! 👍

2019-12-10 08:02 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/application/service/PaymentInternalService.java
> +    private PaymentRepository paymentRepository;
Spring에서 의존성 주입은 생성자 주입 방법을 권장한다고 배웠습니다.
https://landsnail.tistory.com/entry/Spring-%EC%9D%98%EC%A1%B4%EC%84%B1-%EC%A3%BC%EC%9E%85-%EB%B0%A9%EB%B2%95
글 읽어보시면 좋을 것 같아요

2019-12-10 08:02 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/exception/InvalidPaymentWayException.java
> +public class InvalidPaymentWayException extends RuntimeException {
😄

2019-12-10 08:02 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/payment/Payment.java
> +        this.customerId = Objects.requireNonNull(customerId);
`requireNonNull` 사용 좋네요 👍

2019-12-10 08:02 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/payment/PaymentMethod.java
> +    MEET_CREDIT_CARD("만나서 카드결제");
만나서 현금결제, 만나서 카드 결제로 나누기 보단
만나서 결제   하나로만 해도 괜찮지 않을까요..?

2019-12-10 08:02 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/domain/payment/PaymentMethod.java
> +        throw new InvalidPaymentWayException();
depth를 줄이기 위해 stream을 제안해요.

~~~ java
Arrays.stream(PaymentMethod.values()).filter(paymentMethod -> paymentMethod.isMatches(paymentWay))
            .findAny()
            .orElseThrow(InvalidPaymentWayException::new);

// isMatches 메서드
public boolean isMatches(final String paymentWay) {
        return this.method.equals(paymentWay);
    }
~~~

2019-12-11 04:58 UTC, kangmin46 commented on src/main/java/com/woowacourse/caffeine/domain/payment/PaymentMethod.java
> +    MEET_CREDIT_CARD("만나서 카드결제");
좋은 지적입니다~

2019-12-11 06:06 UTC, Laterality requested changes

2019-12-11 06:06 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/dto/PaymentResponse.java
> +    private final String way;
다른 클래스와 이름을 통일하면 어떨까요?

2019-12-11 06:06 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/service/PaymentInternalService.java
> +    public PaymentResponse retrieve(final long customerId) {
`retrieve`라는 이름에는 메서드가 어떤 기능인지 구체적으로 나타나지 않는 것 같아요.

2019-12-11 06:06 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/payment/Payment.java
> +            throw new InvalidIdException();
구체적인 예외를 반환하면 좋을 것 같아요.

2019-12-11 06:06 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/payment/PaymentMethod.java
> +    public static PaymentMethod match(final String paymentWay) {
인자 이름도 같이 바꾸면 어떨까요?

2019-12-11 06:06 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/payment/PaymentMethod.java
> +    public static PaymentMethod match(final String paymentWay) {
메서드 이름도 `from`같은 걸로 바꿔보면 어떨까요?

2019-12-11 06:06 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/payment/Payment.java
> +    private Long paymentId;
별도로 관계 매핑은 없는 엔티티인가요?

2019-12-11 06:06 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/repository/PaymentRepository.java
> +    Payment findByCustomerId(long customerId);
Customer : Payment 는 1: N 관계인 것 같은데, 반환타입에 컬렉션을 쓰는 건 어떨까요?

2019-12-12 07:42 UTC, closed without merging