Menu에 관한 Spring Rest docs 추가
EDD-season2/caffeine-be pull request #31
Opened 2019-12-12 07:18 UTC by Conatuseus

## rest docs 외 추가 내용
MenuItemResponse의  
vender의 자료형을 변경했습니다.
기존: String
변경 후: ShopResponse

2019-12-12 08:16 UTC, yuyu154 requested changes

2019-12-12 08:16 UTC, yuyu154 commented on src/docs/asciidoc/index.adoc
> +
"== Menu API" 를 작성해서 소제목 형식으로 해보면 좋을 것 같네요

2019-12-12 08:16 UTC, yuyu154 commented on src/docs/asciidoc/index.adoc
> +
response-fields.adoc 도 추가해주면 좋을 것 같네요.

2019-12-17 09:00 UTC, Laterality commented
충돌 생기는 부분이랑 커밋 로그 정리해주세요 😭

2019-12-20 01:20 UTC, yuyu154 approved these changes

2019-12-22 13:38 UTC, closed without merging