ownerAPI 구현
EDD-season2/caffeine-be pull request #45
Opened 2019-12-17 07:16 UTC by kangmin46

회원가입 : v1/owners/signup
로그인 : v1/owners/login
로그아웃 : v1/owners/logout

2019-12-17 07:35 UTC, Laterality requested changes

2019-12-17 07:35 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/dto/SignUpRequest.java
> +    public void setPassword(String password) {
필요한가요?

2019-12-17 07:35 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/service/OwnerInternalService.java
> +    public String login(final LoginRequest loginRequest) {
이름을 바꿔보면 좋을 것 같아요.

2019-12-17 07:35 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/service/OwnerService.java
> +    public String login(final LoginRequest loginRequest) {
이름을 바꿔보면 어떨까요?

2019-12-17 07:35 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/controller/OwnerController.java
> +        return ResponseEntity.ok().build();
`201 CREATED`로 응답을 주면 어떨까요?

2019-12-17 07:35 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/Owner.java
> +        if (shopName.trim().isEmpty() || !Pattern.matches(SHOP_NAME_REGEX, shopName)) {
`checkShopName`에서만 `trim`하면 엔티티에 들어가는 값은 `trim`되지 않은 값이 들어가지 않나요?

2019-12-17 07:35 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/Owner.java
> +    public void checkAuthenticate(String password) {
동사 + 동사 =?

2019-12-17 07:35 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/Owner.java
> +    public String getPassword() {
getter가 필요한가요?

2019-12-17 07:35 UTC, Laterality commented on src/test/java/com/woowacourse/caffeine/controller/OwnerControllerTest.java
> +    @DirtiesContext
DBUnit과 Dirty Context를 같이 사용하신 이유가 있나요?

2019-12-17 07:37 UTC, kangmin46 commented on src/main/java/com/woowacourse/caffeine/domain/Owner.java
> +    public String getPassword() {
네 필요해여

2019-12-17 07:58 UTC, yuyu154 commented on src/main/java/com/woowacourse/caffeine/controller/OwnerController.java
> +    @PostMapping("/signup")
POST v1/owners 이런식으로 요청해도 되지 않을까요?

2019-12-17 08:53 UTC, Laterality requested changes

2019-12-17 08:53 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/service/OwnerInternalService.java
> +    public OwnerResponse findByEmail(final String email) {
`readOnly=true`

2019-12-17 08:53 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/service/OwnerService.java
> +    public String authenticate(final LoginRequest loginRequest) {
`readOnly=true`

2019-12-17 08:53 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/controller/OwnerController.java
> +        httpSession.setAttribute("email", email);
"email"을 상수처리하면 어떨까요?

2019-12-17 08:53 UTC, Laterality commented on src/test/java/com/woowacourse/caffeine/controller/OwnerControllerTest.java
> +    @DisplayName("사장님 로그인 테스트")
실패한 케이스들은 테스트가 없는 것 같아요

2019-12-18 04:25 UTC, Laterality approved these changes

2019-12-18 04:31 UTC, yuyu154 approved these changes

2019-12-18 05:10 UTC, merged