Shop name, address 기반 검색 API
EDD-season2/caffeine-be pull request #54
Opened 2019-12-24 06:49 UTC by kangmin46

API문서는 RestDocs를 참고해 주세요

요청예시 : v1/search/?query=keyWord%3Dname, contents%3D송파구

2019-12-24 07:20 UTC, Conatuseus reviewed
저는 SearchController보다 해당 도메인 컨트롤러에 서치 기능이 있으면 좋겠어요.

2019-12-24 07:20 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/application/service/SearchService.java
> +    private final SearchInternalService searchInternalService;
한 띄 어 ?

2019-12-24 07:20 UTC, Conatuseus commented on src/main/java/com/woowacourse/caffeine/presentation/controller/SearchController.java
> +public class SearchController {
ShopController에서 search를 하는건 어떨까요? 
ex) localhost:8080/v1/shops?search=~~

2019-12-25 09:27 UTC, Laterality requested changes
검색 옵션을 각각의 쿼리 파라미터가 아니라 단일 파라미터로 받아 직접 파싱하시는 이유가 있나요?

2019-12-25 09:27 UTC, Laterality commented on build.gradle
> +
필요한 변경사항일까요?

2019-12-25 09:27 UTC, Laterality commented on src/docs/asciidoc/index.adoc
> +== search-API
*.adoc 파일은 CI 프로세스에서 API 문서를 생성할 때 사용하는 파일인데요. 굳이 저장소에서 관리할 필요는 없을 것 같아요.

2019-12-25 09:27 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/application/service/ShopInternalService.java
> +    public Page<ShopResponse> search(final ShopSearchDto shopSearchDto, final Pageable pageable, final SearchFunction searchFunction) {
Internal service에서 엔티티를 VO로 변환하는 게 적절할까요?
만약 다른 서비스에서 검색 결과를 엔티티로 사용할 필요가 생긴다면?

2019-12-25 09:27 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/SearchFunction.java
> +public interface SearchFunction {
`SearchFunction` 이라는 이름은 여러 종류의 검색에 다양하게 활용할 수 있는 것 처럼 보이지만, 인자나 반환타입을 보면  `Shop` 엔티티에 종속된 것이 아닐까요?

2019-12-25 09:27 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/support/SearchParser.java
> +public class SearchParser {
클래스의 구체적인 역할을 주석으로 명시해주면 이해하기 더 좋을 것 같아요 :)

2019-12-25 09:27 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/support/SearchParser.java
> +    private static final String SEARCH_KEY_VALUE_SPLIT_DELIMITER = "%3D";
아래와 같이 표현하면 어떤 값인지 한눈에 알 수 있지 않을까요?
```suggestion
    private static final String SEARCH_KEY_VALUE_SPLIT_DELIMITER = URLEncoder.encode("=", "utf-8");
```

2019-12-25 10:10 UTC, kangmin46 commented on src/main/java/com/woowacourse/caffeine/support/SearchParser.java
> +    private static final String SEARCH_KEY_VALUE_SPLIT_DELIMITER = "%3D";
오 이런방법이있었군요~

2019-12-25 16:17 UTC, eunsukko commented on src/main/java/com/woowacourse/caffeine/support/SearchParser.java
> +    private static final String SEARCH_KEY_VALUE_SPLIT_DELIMITER = "%3D";
혹시 이 부분 실제로 돌려서 확인이 된걸까요??

실제로 돌려서 해보니..  스프링에서 알아서 '=' 로 바꿔서 
```java
public Page<ShopResponse> search(final String query, final Pageable pageable) 
``` 
여기에 query 에 채워주는 것 같아서요.

'query=keyWord%3Daddress,contents%3D오금로' 인 경우
query 에는 'keyWord=address,contents=오금로' 이렇게 들어오는 것 같아요

2019-12-26 01:14 UTC, kangmin46 commented on src/main/java/com/woowacourse/caffeine/support/SearchParser.java
> +    private static final String SEARCH_KEY_VALUE_SPLIT_DELIMITER = "%3D";
![image](https://user-images.githubusercontent.com/40996389/71452441-7bab7c80-27c8-11ea-9d81-41e44d4b63a1.png)
일단 디버깅 할 때에는 이렇게 들어오긴 해요

2019-12-26 01:37 UTC, kangmin46 commented on build.gradle
> +
일단 그렇게 한 이유는 페이징 처리랑 검색 옵션을 구분짓기 위해서 그렇게 했었는데 파서가 마음에 안들어서 그냥 지워버렸습니다~

2019-12-26 02:01 UTC, Laterality approved these changes

2019-12-26 02:01 UTC, Laterality commented on src/main/java/com/woowacourse/caffeine/domain/SearchKeyWord.java
> +public enum SearchKeyWord {
`keyword`가 한 단어이니 KeyWord 보다는 Keyword가 적당한 것  같아요.

2019-12-26 02:08 UTC, merged